version: '3'
services:
  web:
    image: $ORG/${APP}_$ENV:$TAG
    container_name: $APP
    hostname: $ORG-$APP
    volumes:
      - ../../:/srv
    ports:
      - 80:80
    env_file:
      - web.env
    command: /srv/deployment/run.sh
