version: '3'
services:
  web:
    image: $DHOST/$ORG/${APP}_$ENV:$TAG
    hostname: $ORG-$APP
    volumes:
      - /srv:/srv
    ports:
      - 443:443
    command: /srv/deployment/run.sh
    logging:
      driver: awslogs
      options:
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-group: $APP-$ENV-logs
        awslogs-stream-prefix: $ORG
